# Generated by Django 5.0.4 on 2024-10-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='Ticketnum',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
