# Generated by Django 5.0.4 on 2024-12-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleApp', '0002_alter_weight_ticketnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='TenCan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='Firstweight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='Netweight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='Secondweight',
            field=models.IntegerField(default=0),
        ),
    ]
