# Generated by Django 5.0.4 on 2024-06-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScaleName', models.CharField(max_length=255)),
                ('CreatDay', models.DateTimeField(auto_now_add=True, null=True)),
                ('State', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
