# Generated by Django 5.0.4 on 2024-06-11 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleApp', '0002_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='CanId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ScaleApp.scale'),
        ),
    ]
