# Generated by Django 5.0.4 on 2024-06-11 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleApp', '0003_weight_canid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='UserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
