# Generated by Django 5.0.4 on 2024-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
