# Generated by Django 5.0.4 on 2024-04-06 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0002_user_phone_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieucan',
            name='TenCan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CanApp.thongtincan'),
        ),
    ]
