# Generated by Django 5.0.4 on 2024-05-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
