# Generated by Django 5.0.4 on 2024-05-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
