# Generated by Django 5.0.4 on 2024-05-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtincan',
            name='NgayTao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
