# Generated by Django 5.0.4 on 2024-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0008_alter_thongtincan_ngaytao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieucan',
            name='NgayTao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='thongtincan',
            name='NgayTao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
