# Generated by Django 5.0.4 on 2024-05-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0009_alter_phieucan_ngaytao_alter_thongtincan_ngaytao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phieucan',
            old_name='TenCan',
            new_name='CanId',
        ),
    ]
