# Generated by Django 5.0.4 on 2024-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0012_alter_phieucan_ngaytao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieucan',
            name='TLHang',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
