# Generated by Django 5.0.4 on 2024-05-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0015_alter_thongtincan_options_user_namecompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='NameCompany',
            new_name='Company',
        ),
    ]
