# Generated by Django 5.0.4 on 2024-05-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0016_rename_namecompany_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Company',
            new_name='company',
        ),
    ]
