# Generated by Django 5.0.4 on 2024-06-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0018_customer_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='Custcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CanApp.customer'),
        ),
        migrations.AddField(
            model_name='weight',
            name='Prodcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CanApp.product'),
        ),
    ]
