# Generated by Django 5.0.4 on 2024-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0019_weight_custcode_weight_prodcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='Note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
