# Generated by Django 5.0.4 on 2024-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0020_alter_weight_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='Note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
