# Generated by Django 5.0.4 on 2024-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0021_alter_weight_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='CustName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='ProdName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
