# Generated by Django 5.0.4 on 2024-06-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0022_weight_custname_weight_prodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='Ticketnum',
            field=models.CharField(max_length=255),
        ),
    ]
