# Generated by Django 5.0.4 on 2024-06-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanApp', '0023_alter_weight_ticketnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='Docnum',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weight',
            name='Truckno',
            field=models.CharField(max_length=15),
        ),
    ]
