# Generated by Django 5.0.3 on 2024-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanDienTu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinCan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCan', models.CharField(max_length=255)),
            ],
        ),
    ]
