# Generated by Django 4.2.7 on 2024-04-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanDienTu', '0002_thongtincan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
