# Generated by Django 4.2.7 on 2024-04-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanDienTu', '0003_user_active_user_avatar_user_phone_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
