# Generated by Django 4.2.7 on 2024-04-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CanDienTu', '0004_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieucan',
            name='TenCan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CanDienTu.thongtincan'),
        ),
    ]
